//emergencyStore
export const TOGGLE_PLAN_MODEL = 'TOGGLE_PLAN_MODEL'

export const INIT_TEMP_NAMES = 'INIT_TEMP_NAMES'
export const INIT_RELATEORGS = 'INIT_RELATEORGS'
export const INIT_DEPS = 'INIT_DEPS'
export const INIT_TYPES = 'INIT_TYPES'
export const INIT_ADD_DUITES = 'INIT_ADD_DUITES'
export const INIT_LEVELS = 'INIT_LEVELS'
export const INIT_TEMPLATE = 'INIT_TEMPLATE'
export const INIT_DUTIES = 'INIT_DUTIES'
export const TOGGLE_DUTY = 'TOGGLE_DUTY'
export const DELETE_DUTY = 'DELETE_DUTY'
export const ADD_NEW_DUTY = 'ADD_NEW_DUTY'
export const TOGGLE_TEMP_DUTY = 'TOGGLE_TEMP_DUTY'
export const DELETE_TEMP_DUTY = 'DELETE_TEMP_DUTY'
export const DO_REFRESH_PLAN = 'DO_REFRESH_PLAN'

export const INIT_NEW_TEMPLATE = 'INIT_NEW_TEMPLATE'
export const TOGGLE_NEW_TEMPLATE = 'TOGGLE_NEW_TEMPLATE'

//systemStore
export const STORE_LOGIN_USER = 'STORE_LOGIN_USER'
export const TOGGLE_LOGIN_PAGE = 'TOGGLE_LOGIN_PAGE'

//basicInfoStore
export const TOGGLE_BASIC_INFO_POPUP = 'TOGGLE_BASIC_INFO_POPUP'
export const ADD_GEO_COLLECTION = 'ADD_GEO_COLLECTION'
export const ADD_POI_CLICK_EVENT = 'ADD_POI_CLICK_EVENT'
export const REMOVE_GEO_COLLECTION = 'REMOVE_GEO_COLLECTION'
export const REMOVE_POI_CLICK_EVENT = 'REMOVE_POI_CLICK_EVENT'
export const SHOW_MATERIAL_LIST = 'SHOW_MATERIAL_LIST'
export const HIDE_POI_DETAIL_POPUP = 'HIDE_POI_DETAIL_POPUP'
export const CLEAR_ALL_GEO_POI = 'CLEAR_ALL_GEO_POI'
export const MATCH_GEO_POI = 'MATCH_GEO_POI'
export const TOGGLE_GEO_INFO_POPUP = 'TOGGLE_GEO_INFO_POPUP'
export const CLEAR_SELECTED_PRI = 'CLEAR_SELECTED_PRI'

//monitorStore
export const CHANGE_REAL_POPUP = 'CHANGE_REAL_POPUP'