export const secondMenuClassName = {
  nsm8: 's-eight',
  nsm9: 's-nine',
  nsm10: 's-ten',
  nsm12: 's-twelve',
  nsm13: 's-thirteen',

  nsm17: 's-seventeen',
  nsm18: 's-eighteen',
  nsm19: 's-nineteen',
  nsm20: 's-twenty',
  nsm21: 's-twentyone',
  nsm22: 's-twentytwo',
  nsm23: 's-twentythree',
  nsm24: 's-twentyfour',
  nsm25: 's-twentyfive',
  nsm26: 's-twentysix',
  nsm27: 's-twentyseven',
  nsm28: 's-twentyeight',
  nsm29: 's-twentynine',
  nsm30: 's-thirty',

  nsm31: 's-thirtyone',
  nsm32: 's-thirtytwo',
  nsm33: 's-thirtythree',
  nsm34: 's-thirtyfour',
  nsm36: 's-thirtysix',
  nsm37: 's-thirtyseven',

  nsm38: 's-thirtyeight',
  nsm39: 's-thirtynine',
  nsm40: 's-fourty',
  nsm41: 's-fourtyone',
  nsm42: 's-fourtytwo',
  nsm43: 's-fourtythree',
  nsm44: 's-fourtyfour',
  nsm45: 's-fourtyfive',
  nsm46: 's-fourtysix',
  nsm47: 's-fourtyseven',
  nsm48: 's-fourtyeight',
  nsm49: 's-fourtynine',
  nsm50: 's-fifty',
  nsm51: 's-fiftyone',
  nsm52: 's-fiftytwo',
  nsm53:'s-fiftythree',
  nsm54:'s-fiftyfour',
  nsm55:'s-fiftyfive',
  nsm59:'s-fiftynine',
  nsm56:'s-fiftysix',
  nsm57:'s-fiftyseven',
  nsm58:'s-fiftyeight',
  nsm60:'s-sixty',
  nsm64:'s-sixtyfour',
  nsm65: 's-sixtyfive',
  nsm121:'s-onehundredtwentyone',
  nsm122:'s-onehundredtwentytwo',
  nsm123:'s-onehundredtwentythree',
  nsm200:'s-twohundred',
  nsm222:'s-twohundredtwentytwo',
  nsm300:'s-threehundred',
}
export const thridMenuClassName = {
  ntm1: 't-one',
  ntm2: 't-two',
  ntm3: 't-three',
  ntm4: 't-four',
  ntm5: 't-five',
  ntm6: 't-six',
  ntm7: 't-seven',
  ntm8: 't-eight',
  ntm9: 't-nine',
  ntm10: 't-ten',
  ntm11: 't-eleven',
  ntm12: 't-twelve',
  ntm13: 't-thirteen',
  ntm14: 't-fourteen',
  ntm15: 't-fifteen',
  ntm16: 't-sixteen',
  ntm17: 't-seventeen',
  ntmc5555U: 't-eighteen',
}