export const windRadar = 'nsm23' //风廓线雷达
export const airDetect = 'nsm121' //探空云分析
export const localCloud = 'nsm13' //本地云模式
export const shortForecast = 'nsm8'  //短期预报
export const micradiation = 'nsm53'  //微波辐射计
export const actualproduct = 'nsm22'  //实况产品
export const ecwmfInter = 'nsm9'  //ECWMF细网格模式产品 
export const sunflower = 'nsm19'  //葵花8红外灰度图 
// export const windradar = 'nsm23' //风廓线雷达
// export const reservoirLevel = '2' //水库水位
export const satelliteProduct = 'nsm20'  //卫星云反演产品
export const grapesMode = 'nsm10' //grapes中尺度模式产品
export const reservoirLevel = '3-ntm2' //水库水位
export const cityShortForecast = 'nsm12'
export const riverLevel = '3-ntm3' //河流水位
export const cityFire = '3-ntm12' //城市火险
export const forestFire = '3-ntm11' //森林火险
export const dryCondition = '3-ntm1' // 干旱
export const grapes1km = 'nsm18'
export const grapes3km = 'nsm17'
export const mountainFlood = "3-ntm9"
export const environmentPublic = "3-ntm15" //环境公报
export const airQuality = "3-ntm16"   //空气质量3天预报
export const environmentForecast = "3-ntm17" //环境气象预报
export const HumanComfort = "3-ntm14" //人体舒适度
export const SunstrokeIndex = "3-ntm13" //中暑指数
export const weatherForecast = '3-ntm6' //气候预测
export const agricultureAnalysis = '3-ntm4' //农情分析
export const satelliteCloud = 'nsm60'  //卫星云图产品
export const personalManagement = 'nsm48' //人员管理
export const shortRadar = 'nsm21'  //短临产品和雷达综合分析
export const midLongForecast = '3-ntm5' //中长期预报
export const typh = 'nsm64'  //台风
export const airplaneCommand = 'nsm122'  //飞机轨迹设计
export const messageDispatch = 'nsm56' //短信调度
export const jobManagement = 'nsm65' //作业点管理 
export const abilityEstimate = 'nsm51'  //能力评估  
export const disasterManage = 'nsm44'  //灾情管理
export const ammunitionInternet = 'nsm47'  //弹药装备物联网
export const conditionAudit = 'nsm52'  //地面作业资格条件审核
export const airspaceMonitoring = 'nsm38' //空域预测
export const aircraftCommand = 'nsm29' //飞机作业跟踪指挥
export const groundControl = 'nsm30' //地面作业跟踪指挥
export const phoneLiveMonitor = 'nsm59' //手机直播监测
export const groundMsgCollection = 'nsm39' //地面信息采集
export const orderDispatch = 'nsm222'     //指令调度
export const groundTarget = 'nsm123'   //地面作业指标
export const historyReturn = 'nsm33'  //历史回归
export const ecmwfRain = 'nsm200'            //雨量统计
export const gridRainfall = 'nsm300'    //七天网格预报雨量
export const operateDemandAnalysis = 'nsm1'
export const operateDemandSurvey = 'nsm2'
export const operatePlan = 'nsm11'
export const operatePotential = 'nsm14'
export const operateWarningGroundReport = 'nsm24'
export const operateWarningAirReport = 'nsm26'
export const operateGroundPlan = 'nsm25'
export const operateAirPlan = 'nsm27'
export const operateEffectEvaluating = 'nsm35'

export const phoneLivePanel = 'phoneLivePanel' //直播面板
export const fileManagement = 'nsm50'
export const repoMonitor = 'nsm43'
